### ISSUE TITLE
Go Live checklist

### ISSUE THREAD

**Issue by ftdgoodluck** [NEAR-DevHub/race-of-sloths#135]
Checklist to ensure we're 100% ready for launch

```[tasklist]
### Landing
- [x] Landing working 100% correctly and covers all issues in [Notion](https://www.notion.so/Frontend-changes-34d6a813a25e48ed9687f49c563679d1?d=31650b453ea04edea404d0117ba28384#6e9ac033d7b548208fa58d7e90fd4da5)
- [x] Social previews working
```

```[tasklist]
### Bot
- [x] Messages finalized (texts)
- [x] All links are checked and correct
- [x] Every bot flow is tested and works correctly
- [x] New bot picture
- [x] Deploy contract on mainnet
```

```[tasklist]
### Social
- [x] Alex and Gleb have access to Twitter
- [x] Telegram admins set up
- [ ] Twitter communication plan for 2 weeks
- [x] Avatars set up
- [x] Sloth user github profile
- [x] Blogpost by Vlad
- [x] Twitter bio
- [x] Twitter cover
```

```[tasklist]
### Hosting
- [x] All hosting is paid off, and credit cards connected
- [x] Vlad has admin access on all hosting platforms
```

```[tasklist]
### Monitoring
- [x] Monitoring is set up and running, all developers have access to it
- [x] Bot covered
- [x] Frontend covered
- [x] Backend covered
- [x] Backend errors telegram notifications
- [x] Bot errors telegram notifications
```

```[tasklist]
### Repo maintainers calls with confirmations
- [x] FastNEAR
- [x] BOS
- [x] Ref
- [x] [Nearcore](https://github.com/near/nearcore)
- [x] [near-lake-framework-rs](https://github.com/near/near-lake-framework-rs) + https://github.com/near/read-rpc
- [x] https://github.com/near/near-sdk-rs + https://github.com/near/borsh-rs
- [x] https://github.com/near/near-api-js
- [x] NEAR docs
- [ ] Calimero
- [x] Aurora
```
