### ISSUE TITLE
Grant maintainer SP after scoring

### ISSUE THREAD

**Issue by ftdgoodluck** [NEAR-DevHub/race-of-sloths#193]
Grant maintainer who scored a PR with additional SP
```[tasklist]
### Tasks
- [ ] Grant the person who scored with 25 SP
- [ ] Modify the bot message: under "Current status" block: after the words "You have received X Sloth points for this contribution" add "@maintainer received 25 SP for reviewing and scoring this pull request"
- [ ] Modify the bot message: under "What is the Race of Sloths" section after " Score pull requests that participate in the Race of Sloths" add " and receive a reward"
```
