### ISSUE TITLE
Create Sloth bot role model

### ISSUE THREAD

**Issue by ftdgoodluck** [NEAR-DevHub/race-of-sloths#37]
Create a role model for the bot.

```[tasklist]
### Tasks
- [ ] https://github.com/NEAR-DevHub/devbot/issues/92
- [ ] https://github.com/NEAR-DevHub/devbot/issues/97
- [ ] https://github.com/NEAR-DevHub/devbot/issues/98
- [ ] https://github.com/NEAR-DevHub/devbot/issues/99
- [ ] https://github.com/NEAR-DevHub/devbot/issues/100
- [ ] https://github.com/NEAR-DevHub/devbot/issues/111
```

**Comment by ftdgoodluck** [comment]
List of supported commands:

For contributors:
- @sloth include - includes particular PR in Sloth race

For maintainers:
- @sloth score [1-10] - rates the specific PR that participates in the Sloth race
- @sloth exclude - excludes particular PR from the Sloth race
- @sloth pause - pauses bot for a particular repository

Workflow:

1. Contributor creates a PR with a mention of the Sloth bot using “@sloth include” command
2. The Sloth bot responds with a like emoji over the description and writes a comment“This pull request was submitted for the Sloth race [active link]”.
3. Contributor sends PR for a review
4. Sloth bot writes a comment "This pull request is a part of Sloth race[active link]. Please use the "@sloth reject" command to exclude this pull request from the Sloth race, "@sloth score [1-10]" to rate it, or "@sloth pause" to pause all Sloth race notifications across the project”
5. If the maintainer writes a comment with “@sloth pause” command, the PR is automatically excluded from Sloth race and all bot actions inside the repo are paused
6. If the maintainer writes a comment with “@sloth exclude” command, the PR is excluded from the Sloth race
7. If the maintainer writes a comment with @sloth score X” command, the bot responds with a like emoji over the message and writes a comment “Thanks for submitting your score for the Sloth race [active link]. This score would be recorded once the pull request is merged
8. If the maintainer writes a comment with “@sloth score” command but with an incorrect token that we can’t parse, the bot writes a comment “Please use the score command with the following syntax:  @sloth score + a number between 1 and 10 after a space”


Some thoughts:

- any type of scoring with multiple parameters would result in a longer explanation message, more mistakes from reviewers and thus more useless messages from the bot asking to write a correct response. Are we OK with that, or it would make more sense to have only one parameter? @frol @botezatunear 
- this flow does not touch some edge cases (multiple reviewers, unpausing bot, etc.)
- Once we agree on the flow I'll create a diagram for visual explanation

**Comment by botezatunear** [comment]
I agree that one score will be easier for everyone, I've written thoughts in the [specific task](https://github.com/orgs/NEAR-DevHub/projects/6/views/3?sliceBy%5Bvalue%5D=%5B0%5D+Research+and+planning&pane=issue&itemId=61697358): 

Let's discuss tomorrow and finalise

**Comment by ftdgoodluck** [comment]
blocked by #46 - once the PRD is finalized this task would be updated

**Comment by ftdgoodluck** [comment]
@frol @botezatunear @akorchyn waiting for your comments, gentlemen
