### ISSUE TITLE
MVP launch

### ISSUE THREAD

**Issue by ftdgoodluck** [NEAR-DevHub/race-of-sloths#41]
Epic for MVP launch
```[tasklist]
### Tasks
- [ ] https://github.com/NEAR-DevHub/devbot/issues/6
- [ ] https://github.com/NEAR-DevHub/devbot/issues/7
- [ ] https://github.com/NEAR-DevHub/devbot/issues/8
- [ ] https://github.com/NEAR-DevHub/devbot/issues/9
- [ ] https://github.com/NEAR-DevHub/devbot/issues/10
- [ ] https://github.com/NEAR-DevHub/devbot/issues/12
- [ ] https://github.com/NEAR-DevHub/devbot/issues/33
- [ ] https://github.com/NEAR-DevHub/devbot/issues/36
- [ ] https://github.com/NEAR-DevHub/devbot/issues/37
- [ ] Go Live checklist
```
