### ISSUE TITLE
Social accounts

### ISSUE THREAD

**Issue by ftdgoodluck** [NEAR-DevHub/race-of-sloths#47]
```[tasklist]
### Tasks
- [ ] https://github.com/NEAR-DevHub/devbot/issues/48
- [ ] https://github.com/NEAR-DevHub/devbot/issues/49
- [ ] https://github.com/NEAR-DevHub/devbot/issues/50
```
