### ISSUE TITLE
Project landing page

### ISSUE THREAD

**Issue by ftdgoodluck** [NEAR-DevHub/race-of-sloths#9]
Implement landing page

- project description
- call to action
- rules
```[tasklist]
### Tasks
- [ ] https://github.com/NEAR-DevHub/devbot/issues/51
- [ ] https://github.com/NEAR-DevHub/devbot/issues/71
- [ ] https://github.com/NEAR-DevHub/devbot/issues/70
- [ ] https://github.com/NEAR-DevHub/devbot/issues/76
- [ ] https://github.com/NEAR-DevHub/devbot/issues/69
- [ ] https://github.com/NEAR-DevHub/devbot/issues/72
- [ ] https://github.com/NEAR-DevHub/devbot/issues/68
- [ ] https://github.com/NEAR-DevHub/devbot/issues/67
- [ ] https://github.com/NEAR-DevHub/devbot/issues/66
```
